config/routes.rb
Rails.application.routes.draw do
get 'home/index'
root 'home#index'
get '/products', to: 'products#index'
get '/products/new', to: 'products#new'
post '/products', to: 'products#create'
get '/products/:id', to: 'products#show', as: 'product'
get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
patch '/products/:id', to: 'products#update'
put '/products/:id', to: 'products#update'
delete '/products/:id', to: 'products#delete'
  #resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def index
@products = Product.all
end
def new
@product = Product.new
end
def create
@product = Product.new(product_params)
  if @product.save
    redirect_to products_path
  else
    render :new
  end
end
def edit
@product = Product.find(params[:id])
end
def update
  @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
end
def delete
  @product = Product.find(params[:id])
  @product.destroy
  redirect_to products_path
end
private
def product_params
  params.require(:product).permit(:name, :description, :price)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-fast  fixed-top shadow-lg">
    <div class="container">
                <a class="navbar-brand js-scroll-trigger font-logo" href="#page-top">FastNomina</a>
                <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-light text-primary rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">

                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link js-scroll-trigger" href="#about"><button type="button" class="btn btn-sm btn-light btn-nav">Iniciar sesión</button>
						</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link  js-scroll-trigger" href="#contact"><button type="button" class="btn btn-sm btn-light btn-nav ">Regístrate</button></a></li>
                    </ul>
                </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Proyecto</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
<div>
<%= f.label :name %>
<%= f.text_field :name %>
</div>
<div>
<%= f.label :description %>
<%= f.text_area :description %>
</div>
<div>
<%= f.label :price %>
<%= f.number_field :price %>
</div>
<div>
<%= f.submit %>
</div>
<% end %>

app/views/products/index.html.erb
<h1>Listado de productos</h1>
<h2><%= icon('fas', 'flag') %> </h2>
<table>
  <tr>
  <thead>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Precio</th>
  </thead>
  </tr>
  <% @products.each do |product| %>
  <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td>
        <%= link_to "Mostrar" %>
        <%= link_to "Editar", edit_product_path(product) %>
        <%= link_to "Eliminar", product, method: :delete, data: {confirm:"Deseas eliminar este articulo?"} %>
      </td>
  </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
<div>
<%= f.label :name %>
<%= f.text_field :name %>
</div>
<div>
<%= f.label :description %>
<%= f.text_area :description %>
</div>
<div>
<%= f.label :price %>
<%= f.number_field :price %>
</div>
<div>
<%= f.submit %>
</div>
<% end %>